title: "Soumen Das"
email: "dsoumen65@protonmail.com"
description: "Senior Accounts Executive | GST, TDS, Financial Reporting"
baseurl: "" 
url: "https://yourusername.github.io/soumen-resume"
linkedin_username: soumen-das-7638a9266
theme: jekyll-theme-minimal
